# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 21:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parascopish', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_description',
            field=models.CharField(default=datetime.datetime(2017, 8, 28, 21, 0, 51, 751893, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
