# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-28 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('parascopish', '0004_post_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default=datetime.datetime(2017, 8, 28, 22, 43, 47, 707646, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
    ]
