# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-29 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parascopish', '0007_auto_20170829_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
